spring:
  # Configuración de la aplicación
  application:
    name: atenciones-microservice
  # Configuración de la base de datos
  datasource:
    url: jdbc:mysql://localhost:3307/db_hospital_vm_atenciones
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Configuración de Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
server:
  # Configuración del servidor
  port: 8082
  servlet:
    context-path: /api
services:
  # Configuración de servicios externos
  pacientes:
    baseUrl: http://localhost:8081/api/v1/pacientes
